### ISSUE TITLE
Can't subscribe on new docs

### ISSUE THREAD

**Issue by LeeSwagger** [arianrhodsandlot/Quick-DevDocs#2]
I'm add jQuery in devdocs.io, but nothing changed in quick devdocs library list(

P.S. Hmm, after downloading new docs (in "Offline" tab of devdocs) and reopening browser, new docs successfully loaded)

**Comment by arianrhodsandlot** [comment]
The reason seems to be that http://devdocs.io change it cookies' domain from "devdocs.io" to ".devdocs.io", so the extension's cookies watcher ignores it... I'm going to fix it as soon as possible.
As a temporary solution, you can disable the extension, and then enable it in Chrome's setting page.
Thanks for your feedback!
